version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest-windowsservercore"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    container_name: "efserver"
    hostname: "efserver"
    tty: true
  jboss:
    image: electricflow/jboss7:v7.0-win
    environment:
      - JBOSS_MODE=domain
    ports:
      - "7808:7808"
      - "8080:8080"
      - "9990:9990"
      - "9999:9999"
      - "8230:8230"
      - "8330:8330"
    container_name: jboss7.0-win
    tty: false
networks:
  default:
    external:
      name: nat