version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest-windowsservercore"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    container_name: "efserver"
    hostname: "efserver"
    tty: true
  jboss:
    image: electricflow/jboss7:v7.0-win
    environment:
      - EF_SERVER_HOST=efserver
      - EF_SERVER_ADMIN_USER=admin
      - EF_SERVER_ADMIN_PASS=changeme
      - EF_RESOURCE_NAME=JBOSS
      - SERVER_CONFIG=standalone-full.xml
      - JBOSS_MODE=standalone
    ports:
      - "7808:7808"
      - "8080:8080"
      - "9990:9990"
    container_name: jboss7.0-win
    hostname: "jboss"
    tty: false
networks:
  default:
    external:
      name: nat