version: '3'
services:
  electric-flow:
    image: "electricflow/efserver:latest-windowsservercore"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    container_name: "efserver"
    hostname: "efserver"
    tty: true
  jboss:
    image: "electricflow/jboss6:v6.4-win"
    environment:
      - EF_SERVER_HOST=efserver
      - EF_SERVER_ADMIN_USER=admin
      - EF_SERVER_ADMIN_PASS=changeme
      - EF_RESOURCE_NAME=JBOSS
      - JBOSS_MODE=domain
      - JBOSS_PASSWORD=changeme1!
    ports:
      - "7808:7800"
      - "8080:8080"
      - "9990:9990"
      - "9999:9999"
      - "8230:8230"
      - "8330:8330"
    container_name: "jboss64domain"
    hostname: "jboss64domain"
    tty: false
networks:
  default:
    external:
      name: nat