version: '3'
services:
  electric-flow:
    image: "ecdocker/eflow-ce-server"
    ports:
      - "8000:8000"
      - "8443:8443"
      - "443:443"
      - "80:80"
    networks:
      - internal
    container_name: electricflow
    tty: true
  jboss:
    image: electricflow/jboss7:v7.0
    environment:
      - SERVER_CONFIG=standalone-full.xml
      - JBOSS_MODE=standalone
    ports:
      - "7808:7808"
      - "8080:8080"
      - "9990:9990"
    networks:
      - internal
    container_name: jboss7.0
    tty: true
networks:
  internal:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.29.1.0/24